_wandb:
    value:
        cli_version: 0.23.0
        e:
            65isw5oltdyuwwy2pwu7cjrnp2t67j31:
                args:
                    - --config=configs/autoencoder.py:fae
                    - --config.training.use_pde=True
                codePath: damp_sine/main.py
                codePathLocal: main.py
                cpu_count: 64
                cpu_count_logical: 64
                disk:
                    /:
                        total: "469905842176"
                        used: "38374694912"
                email: 1598935138@qq.com
                executable: /public/home/hnust15111216958/miniconda3/envs/fundiff2/bin/python
                git:
                    commit: 3a663722ea8ed9f1da98f67a1af22445f7f488c2
                    remote: https://github.com/sifanexisted/fundiff.git
                host: bb37bb39a5a5
                memory:
                    total: "267685502976"
                os: Linux-4.18.0-305.3.1.el8.x86_64-x86_64-with-glibc2.35
                program: /public/home/hnust15111216958/zyq/fundiff/fundiff/fundiff/damp_sine/main.py
                python: CPython 3.11.14
                root: /public/home/hnust15111216958/zyq/fundiff/fundiff/fundiff/damp_sine
                startedAt: "2025-12-29T15:22:58.945918Z"
                writerId: 65isw5oltdyuwwy2pwu7cjrnp2t67j31
        m: []
        python_version: 3.11.14
        t:
            "1":
                - 1
                - 5
                - 12
                - 45
                - 53
            "2":
                - 1
                - 5
                - 12
                - 45
                - 53
            "3":
                - 2
                - 13
                - 15
                - 16
                - 61
            "4": 3.11.14
            "5": 0.23.0
            "12": 0.23.0
            "13": linux-x86_64
coords_dim:
    value:
        - 1
dataset:
    value:
        num_samples: 1000
        num_sensors: 64
        num_workers: 1
        test_batch_size: 32
        train_batch_size: 64
logging:
    value:
        eval_interval: 500
        log_interval: 200
lr:
    value:
        decay_rate: 0.95
        init_value: 1e-06
        peak_value: 8e-05
        transition_steps: 2000
        warmup_steps: 500
mode:
    value: train_autoencoder
model:
    value:
        decoder:
            dec_depth: 2
            dec_emb_dim: 256
            dec_num_heads: 8
            fourier_freq: 1
            layer_norm_eps: 1e-05
            mlp_ratio: 1
            num_mlp_layers: 2
            out_dim: 1
        encoder:
            depth: 6
            emb_dim: 256
            grid_size:
                - 50
            layer_norm_eps: 1e-05
            mlp_ratio: 1
            num_heads: 8
            num_latents: 25
            patch_size:
                - 2
        model_name: FAE
optim:
    value:
        beta1: 0.9
        beta2: 0.999
        clip_norm: 1
        eps: 1e-08
        weight_decay: 1e-05
saving:
    value:
        num_keep_ckpts: 3
        save_interval: 500
seed:
    value: 42
training:
    value:
        max_steps: 5000
        num_queries: 10
        random_sensors: false
        sensor_range:
            - 50
            - 100
        use_pde: true
wandb:
    value:
        project: fundiff_geoelectric_1d
        tag: rho_phase_to_res
x_dim:
    value:
        - 8
        - 50
        - 1
y_dim:
    value:
        - 8
        - 50
        - 1
